-- MySQL Script generated by MySQL Workbench
-- Wed Jul 23 20:24:22 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `ylcmanage`.`ylc_manage_product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ylcmanage`.`ylc_manage_product_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL COMMENT '产品大类名（个人借贷产品、公司借贷产品、债权转让类产品、信托/资管产品）',
  `description` VARCHAR(255) NULL COMMENT '描述',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `ylcmanage`.`ylc_manage_product_category_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ylcmanage`.`ylc_manage_product_category_item` (
  `id` INT NOT NULL,
  `product_category_id` INT NOT NULL COMMENT '产品大类',
  `product_name` VARCHAR(255) NOT NULL COMMENT '产品名字',
  `lend_period` INT NULL COMMENT '理财产品出借期限，以天为单位',
  `repayment_method` VARCHAR(45) NULL COMMENT '还款方式（按月还款等额本息、到期还款本金利息、按月还款利息到期还款本金）',
  `service_rate` FLOAT NULL COMMENT '服务费率',
  `annualized_gain` FLOAT NULL COMMENT '预期年化收益率',
  `total_investment` FLOAT NULL COMMENT '投资总金额',
  `minimum_purchase_amount` FLOAT NULL COMMENT '最低购买金额',
  `can_early_redemption` TINYINT NULL DEFAULT 0 COMMENT '是否可提前赎回',
  `early_redemption_fee` FLOAT NULL COMMENT '提前赎回手续费率',
  `description` VARCHAR(255) NULL COMMENT '描述',
  `can_automatic_renewal` TINYINT NULL DEFAULT 0 COMMENT '是否可以自动续期',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`, `product_category_id`),
  INDEX `ylc_manage_product_category_item_ibfk_product_category_id_idx` (`product_category_id` ASC),
  CONSTRAINT `ibfk_product_category_id`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `ylcmanage`.`ylc_manage_product_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `ylcmanage`.`ylc_manage_product_category_item_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ylcmanage`.`ylc_manage_product_category_item_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '产品名称',
  `publish_date` DATETIME NOT NULL COMMENT '发布日期',
  `expiration_data` DATETIME NULL COMMENT '售卖到期时间',
  `remaining_investment_amount` FLOAT NULL COMMENT '剩余可投资金额',
  `guarantee_mode` VARCHAR(45) NULL COMMENT '保障方式（本金保障、本息保障）',
  `single_purchase_limit` FLOAT NULL COMMENT '单人购买上限',
  `description` VARCHAR(1024) NOT NULL COMMENT '产品简介',
  `subscription_status` TINYINT NULL COMMENT '认购状态（未开始、认购中、已满额、计息中）',
  `shelves_status` TINYINT NULL COMMENT '上架状态（未上架、未审核、已上架、已下架）',
  `finish_time` VARCHAR(45) NULL COMMENT '满额用时',
  `product_category_item_id` INT NOT NULL COMMENT '产品小类id',
  `is_newb` TINYINT NULL DEFAULT 0 COMMENT '是否新手',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`, `product_category_item_id`),
  INDEX `ylc_manage_product_category_item_entity_ibfk_product_catego_idx` (`product_category_item_id` ASC),
  CONSTRAINT `ibfk_product_category_item_id`
    FOREIGN KEY (`product_category_item_id`)
    REFERENCES `ylcmanage`.`ylc_manage_product_category_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `ylcmanage`.`ylc_manage_product_investment_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ylcmanage`.`ylc_manage_product_investment_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL COMMENT '客户ID',
  `investment_amount` FLOAT NULL COMMENT '投资总金额',
  `investment_date` DATETIME NULL COMMENT '投标时间',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
